name: CI

on: [push, pull_request]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [stable, beta, nightly]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - run: rustup update ${{ matrix.toolchain }}
      - run: cargo check --all-features

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [stable, beta, nightly]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - run: rustup update ${{ matrix.toolchain }}
      - run: cargo test --all-features

  lints:
    name: Lints
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [stable, beta, nightly]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - run: rustup update ${{ matrix.toolchain }}
      - run: cargo fmt --all-features -- --check
      - run: cargo clippy --all-features -- -D warnings
